### ISSUE TITLE
Symfony 3 remove deprecated mesages

### ISSUE THREAD

**Issue by clacroix** [lightsuner/CarbonBundle#10]
Please surround all class names in all configs yml files with double quotes in order to avoid deprecated messages in Symfony >3. ex: 
class: %carbon.form_extension.carbon_date.class%

to

class: "%carbon.form_extension.carbon_date.class%"

Thanks

**Comment by birkof** [comment]
@lightsuner we need a new release fixing those deprecations

**Comment by lightsuner** [comment]
@birkof I have bumped new version 2.2.0 . Please check.
