### ISSUE TITLE
Framework extra bundle

### ISSUE THREAD

**Issue by brunowego** [lightsuner/CarbonBundle#2]
This package have a dependecy with "framework-extra-bundle" version 2._, but in my case, I have dependencies for "framework-extra-bundle" version 3._.

Is possible update this package to use "framework-extra-bundle" version 3.*? Thanks.

**Comment by lightsuner** [comment]
@brunowego I checked your PR. Everything is ok. I added tag 2.0.0. Please check and thank you for your contribution.

**Comment by brunowego** [comment]
Thanks @lightsuner :+1:
