### ISSUE TITLE
Carbon form extension?

### ISSUE THREAD

**Issue by sandermarechal** [lightsuner/CarbonBundle#4]
Any chance you could add a form type extension so that Symfony's date and datetime types work with Carbon?

**Comment by lightsuner** [comment]
Hi @sandermarechal, thanks for commenting. I will try to do this in 2 weeks.  if you need this feature quicker, you can send PR with code. (At this moment i haven't free time)

**Comment by lightsuner** [comment]
Hey @sandermarechal. Thank you very much!
